### ISSUE TITLE
cannot import dcgan properly

### ISSUE THREAD

**Issue by MichaelShen97** [sugyan/face-generator#3]
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from dcgan import DCGAN
  File "C:\Files\code\py\practice\face-generator\dcgan.py", line 1, in <module>
    submodules/tf-dcgan/dcgan.py
NameError: name 'submodules' is not defined

**Comment by sugyan** [comment]
hmm.. Have you done `$ git submodule update --init` ?

**Comment by MichaelShen97** [comment]
Yes I have. Maybe because it's running in Windows environment?

**Comment by sugyan** [comment]
Maybe, I think so. Unfortunately I don't have a windows machine..
'dcgan.py' is just a symbolic link, so you can copy from https://github.com/sugyan/tf-dcgan/blob/master/dcgan.py and overwritie it.
