### ISSUE TITLE
how to structure the data folder

### ISSUE THREAD

**Issue by qinritukou** [sugyan/face-generator#4]
Because there is no train data. So I wonder how to create train data for training.
Cloud you show me the structure diagram of data folder? Thanks ahead.
And now I have the error below actually.

 Traceback (most recent call last):
  File "train.py", line 111, in <module>
    tf.app.run()
  File "/Users/developer/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in r
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 48, in main
    traindata = inputs(dcgan.batch_size, dcgan.s_size)
  File "train.py", line 28, in inputs
    fqueue = tf.train.string_input_producer(files)
  File "/Users/developer/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 211, i
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

**Comment by WeihongM** [comment]
so do I。
 have you solved this problem？

**Comment by bringtree** [comment]
@WeihongM  @qinritukou so do I。
have you solved this problem？

**Comment by bringtree** [comment]
can't find tfrecords

**Comment by WeihongM** [comment]
@bringtree sorry, I have forgotten.

**Comment by jiangcongmei** [comment]
@WeihongM @qinritukou @bringtree have you solved this problem？
